# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Learning Resources', folder: 'pages', file: 'resources.html'}
- {name: 'Posts', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/BlackRime'}
- {icon: 'facebook', link: 'https://www.facebook.com/profile.php?id=100032965545357'}
- {icon: 'instagram', link: 'https://www.instagram.com/raimverry'}
- {icon: 'envelope', link: 'raimverry96@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
